# Generated by Django 5.0.1 on 2024-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlagData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plag_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_words', models.IntegerField()),
                ('similarity_score', models.FloatField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
